# Generated by Django 2.0.9 on 2018-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeApiError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback', models.TextField(null=True, verbose_name='traceback')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='status')),
                ('message', models.CharField(max_length=255, null=True, verbose_name='message')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='code')),
                ('param', models.CharField(max_length=255, null=True, verbose_name='param')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Stripe API error',
                'verbose_name_plural': 'Stripe API errors',
            },
        ),
    ]
